# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(JSON.stringify(context, null, 2))
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo repo-name=$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'h
        )>> $GITHUB_OUTPUTS
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Versions
      run: |
        python3 --version
    - name: Checkout Current Repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: adafruit/actions-ci-circuitpython-libs
        path: actions-ci
    - name: Install dependencies
      # (e.g. - apt-get: gettext, etc; pip: circuitpython-build-tools, requirements.txt; etc.)
      run: |
        source actions-ci/install.sh
    - name: Pip install Sphinx, pre-commit
      run: |
        pip install --force-reinstall Sphinx sphinx-rtd-theme pre-commit sphinx-autoapi
    - name: Library version
      run: git describe --dirty --always --tags
    - name: Setup problem matchers
      uses: adafruit/circuitpython-action-library-ci-problem-matchers@v1
    - name: Pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Test in circuitpython
      run: ./build-test-cp.sh
    - name: Build assets
      run: circuitpython-build-bundles --package_folder_prefix jepler --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location .
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
    - name: Archive bundles
      uses: actions/upload-artifact@v2
      with:
        name: bundles
        path: ${{ github.workspace }}/bundles/
    - name: Build Python package
      run: |
        pip install --upgrade setuptools wheel twine readme_renderer testresources
        python setup.py sdist
        python setup.py bdist_wheel --universal
        twine check dist/*
